export const techIconOptions = [
  { label: 'JavaScript', value: 'js' },
  { label: 'React', value: 'react' },
  { label: 'Vue.js', value: 'vue' },
  { label: 'Next.js', value: 'nextjs' },
  { label: 'TypeScript', value: 'typescript' },
  { label: 'PHP', value: 'php' },
  { label: 'Laravel', value: 'laravel' },
  { label: 'Python', value: 'python' },
  { label: 'Django', value: 'django' },
  { label: 'Node.js', value: 'node' },
  { label: 'Figma', value: 'figma' },
  { label: 'Sketch', value: 'sketch' },
  { label: 'WordPress', value: 'wordpress' },
  { label: 'Drupal', value: 'drupal' },
  { label: 'Jira', value: 'jira' },
  { label: 'Tailwind CSS', value: 'tailwind' },
  { label: 'AWS', value: 'aws' },
  { label: 'Flutter', value: 'flutter' },
  { label: 'Docker', value: 'docker' },
  { label: 'AI / ML', value: 'ai' },
  { label: 'Shopify', value: 'shopify' },
  { label: 'YouTube', value: 'youtube' },
  { label: 'Cloud', value: 'cloud' },
]